### ISSUE TITLE
ParameterHandler is adding unnecessary quotes to yaml values making it useless

### ISSUE THREAD

**Issue by phackwer** [Incenteev/ParameterHandler#102]
Greetings,

I'm using Phalcon PHP, and decided to use the composer-parameter-handler to update application dist files.

The point is, I'm adding speciffically an exclamation point, since this is what the Phalcon Yaml Reader requires me to do, and for some odd reason, yours paramerter handler keeps adding this unwanted quotes.

Here is how to reproduce the error:

1 - Create a dist file, and add:
database_path:          !app_path /db.sqlite
2 - Do a composer install
3 - Here is the result:
database_path: '!app_path /db.sqlite'

Unfortunatelly the YAML reader can't handle the app_path variable that should be replaced and everything goes to waste.

Any ideas?

**Comment by phackwer** [comment]
Adding the quotes:

SQLSTATE[HY000] [14] unable to open database file
#0 [internal function]: PDO->__construct('sqlite:!app_pat...', NULL, NULL, Array)

No database connection.

Manually removing quotes:
Table 'public'.'pessoa' doesn't exist in database when dumping meta-data for Person\Model\Person

Magic!

**Comment by stof** [comment]
this is because the Symfony YAML reader does not know about the special YAML extension used by Phalcon, and so treats ``!app_path`` as part of the string content.

**Comment by phackwer** [comment]
So, it's all Symfony Yaml Reader's fault?

The Yaml Standard set the following for the ! use:

"The “!” (#x21, exclamation) is heavily overloaded for specifying node tags. It is used to denote tag handles used in tag directives and tag properties; to denote local tags; and as the non-specific tag for non-plain scalars." - http://yaml.org/spec/1.2/spec.html

I reinforce this: It is used to denote tag handles.

It's a handler to allow the adding of values dinamically.

So, I suggest you drop the use of the Symfony Yaml Reader and start use one that fits the standards for PHP.

I wonder why not doing so since the beginning.

http://php.net/manual/en/book.yaml.php

Anyway, I will try a different approach and drop the use of your component. Thank you anyway.
