### ISSUE TITLE
Support for .env besides parameters.yaml?

### ISSUE THREAD

**Issue by dkarlovi** [Incenteev/ParameterHandler#108]
If migrating to Docker, a proper way to enable app container configuration is via [environment variables](https://docs.docker.com/compose/environment-variables/).

This means my Symfony 3.2+ `parameters.yml` looks like

    parameters:
        database_host: '%env(DATABASE_HOST)%'
        database_port: '%env(DATABASE_PORT)%'
        database_name: '%env(DATABASE_NAME)%'
        database_user: '%env(DATABASE_USER)%'
        database_password: '%env(DATABASE_PASSWORD)%'

(meaning I'll probably be able to move it to `config.yml` and remove `parameters.yaml*` altogether) but I still do need to create a `.env` in project root to configure those vars for [docker-compose](https://docs.docker.com/compose/compose-file/#/envfile) usage.

With Symfony 3.3 getting dot-env component and support, is there a way for adding support for `.env` (from `.env.dist` or similar)? It's basically the same thing as existing, only the input/output file is serialized differently.

**Comment by stof** [comment]
The syntax of the .env file can be quit complex. As the dot-env component of Symfony only has a parser, but no dumper, I don't plan to do something like that (I don't want to maintain a dumper here).
Thus, I'm not sure the dot-env parser is suited for parsing and re-dumping a file (which requires that parse+dump ends up being a no-op)

**Comment by dkarlovi** [comment]
@stof agreed. Would you consider it with the dumper being part of Symfony component?

**Comment by stof** [comment]
I'm closing this feature request, as there is now a tool providing such feature: https://github.com/sroze/companienv
