### ISSUE TITLE
Huge composer coupling

### ISSUE THREAD

**Issue by Nek-** [Incenteev/ParameterHandler#112]
I tried to use the parameter handler with deployer. It works great. I like it. But I need to install composer as dev dependency. This is a problem because composer may be in conflict with the local repository. (and well, we all know it's not a good thing to do)

But this project is still cool. That would be nice to decouple the code so it can be reused easily :).

Here is my little experiment:https://gist.github.com/Nek-/99ccfd027f8934a3e26bcc91c3e15587

**Comment by stof** [comment]
Well, this repo is meant to provide a script handler for composer, and so relies on the composer IO abstraction on purpose.
