### ISSUE TITLE
Composer reading parameters.yml.dist

### ISSUE THREAD

**Issue by lecneri** [Incenteev/ParameterHandler#113]
| Q                     | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.8

Hello, I noticed that when we try to add new bundle to symfony and parameters.yml.dist has an error, a parser error is thrown, even though the parameters.yml.dist is correct.

For instance:
* Create a new symfony project
* add a simple space before  mailer_transport entry in app/config/parameters.yml.dist
* go to console and execute
* > composer require jms/serializer-bundle
* An error will be thrown

> Updating the "app/config/parameters.yml" file
> Script Incenteev\ParameterHandler\ScriptHandler::buildParameters handling the symfony-scripts event terminated with an exception
> 
> Installation failed, reverting ./composer.json to its original content.
> 
> 
>   [Symfony\Component\Yaml\Exception\ParseException]
>   Unable to parse at line 13 (near " mailer_transport: smtp").

from error I noticed the following message:
> Updating the "app/config/parameters.yml" file

And acctually it checks parameters.yml.dist, which in my opinion it shouldn't be an issue if this file is wrong since as name says is a distribution file. 

If this file must be parsed, the error message could be more clear and says that parameters.yml.dist has a problem, not the parameters.yml

**Comment by Nek-** [comment]
The file is parsed as yaml file to generate the right parameters.yml file. If it's not valid, how the parameter handler is supposed to help you?

**Comment by lecneri** [comment]
Hi  @Nek-,

Thank you for your answer.

I might get the wrong ideia, but I believe the dist file is a template, thus its contents does not interferes the system development, so its parsing can be ignored.

But lets suppose this file check is done in order to make deployment easier by making sure that every key in parameters.yml and parameters.yml.dist are the same so we won't mess or forget anything when deploying or starting a new development. The error message could be more clear and reference that parameters.yml.dist has an error, but the way the message is shown in console can lead to a misunderstanding and make us check the wrong file.

**Comment by stof** [comment]
Well, this tool is precisely relying on being able to parse the dist file, to synchronize the necessary keys in the actual file. So it needs to have the .yml.dist file being valid YAML
