### ISSUE TITLE
unable to update old value?

### ISSUE THREAD

**Issue by ctx2002** [Incenteev/ParameterHandler#125]
I have a key in parameters.yml file.

`url: 'myurl'`

in parameters.yml.dist file, i have changed the key to:
`url: 'yoururl'`

after run composer run-script post-update-cmd, my parameters.yml file still keeps old value.

in Processor.php file , line 147,

```
foreach ($expectedParams as $key => $message) {
            if (array_key_exists($key, $actualParams)) {
                continue;
            }
```

from above code, looks like old key is not been updated.

**Comment by ctx2002** [comment]
ok, i see, i need to use set "keep-outdated": false, please close this issue

**Comment by ctx2002** [comment]
by the way, in Processor.php

`$actualParams = array_intersect_key($actualParams, $expectedParams);`

why still keep old value?, even keep-outdated set to false.
is not correct one should be 
`$temp = array_intersect_key($expectedParams, $actualParams);`
and then merge $temp with $actualParams

**Comment by stof** [comment]
the dist file is meant to contain the list of config settings, with values used as default value. Keeping the existing configuration set in the actual configuration file is on purpose, so that you don't loose your local configuration each time you run composer.
