### ISSUE TITLE
Exception when using with composer install and PHP 7.2.2

### ISSUE THREAD

**Issue by vbjordan** [Incenteev/ParameterHandler#126]
I am getting the following exception when trying to install using PHP 7.2.2:

```
Script Incenteev\ParameterHandler\ScriptHandler::buildParameters handling the post-install-cmd event terminated with an exception


  [ErrorException]
  A non-numeric value encountered
```

incenteev/composer-parameter-handler                   v2.1.3             Composer script handling your ignored parameter file

Composer version 1.6.4 2018-04-13 12:04:24

PHP 7.2.2

I don't get the error when installing using PHP 5.5

**Comment by dimti** [comment]
I have same issue when isntalling symphony cmf 1.2 on PHP 7.3
I think supported version of PHP 7.1 and install actual symphony release.
Consider requirements: https://packagist.org/packages/symfony-cmf/symfony-cmf
And, on current my case (cmf se 1.2 or 1.3 version) does not work also with php 7.1). But on master branch of CMF SE on 2.0+ release that is work.
