### ISSUE TITLE
Release version which is compatible with symfony 6

### ISSUE THREAD

**Issue by W0rma** [Incenteev/ParameterHandler#141]
Since https://github.com/Incenteev/ParameterHandler/pull/137 `master` is compatible with symfony 6.

However, the latest release is nearly two years old (https://packagist.org/packages/incenteev/composer-parameter-handler#v2.1.4).

Are there any plans to tag a new release?

**Comment by stof** [comment]
I'll do it in the next few days

**Comment by sc0rp10** [comment]
ping @stof

**Comment by W0rma** [comment]
@stof Please let me know if/how I can help to move things forward. I'd be glad to help here.

**Comment by stof** [comment]
Now released. Sorry about the delay, I totally forgot about that pending release.
