### ISSUE TITLE
Add support for phpdotenv

### ISSUE THREAD

**Issue by hason** [Incenteev/ParameterHandler#67]
It would be useful to manage an .env file, see https://github.com/vlucas/phpdotenv.

**Comment by digitalkaoz** [comment]
bump :)

**Comment by digitalkaoz** [comment]
see #71

**Comment by bangpound** [comment]
https://github.com/bangpound/composer-dotenv

Here's a plugin that loads `.env` whenever composer is activated, and those settings are found in the environment when Parameter Handler updates the parameter files after installing or updating.

**Comment by Restless-ET** [comment]
Nice share @bangpound. :)

IMO we could discard #71 and close this in favour of using that plugin.

**Comment by diarmuidie** [comment]
I had a similar requirement in a project so I built a composer package that interactively populates a `.env` file from a `.env.example` in the same way `incenteev/parameterhandle` does.

https://github.com/diarmuidie/EnvPopulate

**Comment by gnutix** [comment]
With Symfony 3.3 Dotenv Component, this feature should definitely be implemented.

**Comment by stof** [comment]
Well, as there are already separate projects above building this feature, I'm not sure it make sense to duplicate this feature in our ParameterHandler.
Use one project or the other (or both in parallel) depending on whether you need to manage a YAML or a dotenv file

**Comment by gnutix** [comment]
I'll do that then! Thought it would make sense as this package is "well known" in the community now, and it could support both features.

**Comment by vyarmolenko** [comment]
+1
It would be great to have dotenv tool like this for yaml - generate local .env from .env.dist with respect to present environment variables.

https://github.com/bangpound/composer-dotenv serves another role - it generates yml from existing dotenv.
https://github.com/diarmuidie/EnvPopulate doesn't have 'env-map' feature which may be useful for generating .env file in automated environments.

**Comment by stof** [comment]
I'm closing this feature request, as there is now a tool providing such feature: https://github.com/sroze/companienv
