### ISSUE TITLE
Copy comments in parameters.yml.dist template 

### ISSUE THREAD

**Issue by trousers** [Incenteev/ParameterHandler#72]
I put Comments #likethis in my config template

It would be very useful if they could be copied along with any additional line breaks to keep things organised

**Comment by stof** [comment]
Comments are not exposed to our library (the point of comments is that they are ignored by the parser).

Writing my own YAML parser (and my own dumper to re-dump comments) which would provide a way to access comments is not an option (thus, I don't see how the returned value could look like to have comments in them while they are not part of the data).

I'm closing this as Won't fix.
