### ISSUE TITLE
Inconsistent backslash escaping in parameter values

### ISSUE THREAD

**Issue by jsmitty12** [Incenteev/ParameterHandler#73]
I have a parameters.yml file with the following line:

```
parameters:
    client_files_dir: "D:\software\client-files"
```

After the parameter handler (v2.1.0) runs it becomes this:
```
parameters:
    client_files_dir: "D:\software\\client-files"
```

I'm not sure if that backslash escaping should occur at all, but it's at least inconsistent as the first backslash is left alone and the second one is escaped.

**Comment by stof** [comment]
The backslash escape comes from the Symfony Yaml component
