### ISSUE TITLE
Release v2.2.0

### ISSUE THREAD

**Issue by nunorafaelrocha** [Incenteev/ParameterHandler#75]
Any roadmap for release v2.2.0 ?

**Comment by stof** [comment]
There is nothing worth a 2.2 release, given there is no new feature in master compared to 2.1, but only a few fixes in the doc: https://github.com/Incenteev/ParameterHandler/compare/v2.1.0...master

Regarding the new features pending in the PRs, I need to find some time to review them. So there is no ETA yet on a release.
