### ISSUE TITLE
Can't use array for generating output parameters file with map-env

### ISSUE THREAD

**Issue by crashev** [Incenteev/ParameterHandler#80]
Hello,
I have settings from parameters.yml.dist mapped like this:
...

```
"incenteev-parameters": {
            "file": "app/config/parameters.yml",

            "env-map": {
                "database_driver":                  "DATABASE_DRIVER",
                 ......
                "pawq_param":                       "PAWQ_PARAM"
            }
        },
```

Now when during generation of parameters.yml I use 

```
$ export PAWQ_PARAM=testvalue
 composer install --optimize-autoloader --no-progress --no-interaction;cat app/config/parameters.yml
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Creating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
Clearing the cache for the dev environment with debug true
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
Trying to install assets as symbolic links.
Installing assets for Symfony\Bundle\FrameworkBundle into web/bundles/framework
The assets were installed using symbolic links.
Installing assets for Sensio\Bundle\DistributionBundle into web/bundles/sensiodistribution
The assets were installed using symbolic links.
Installing assets for Nelmio\ApiDocBundle into web/bundles/nelmioapidoc
The assets were installed using symbolic links.
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile

# This file is auto-generated during the composer install
parameters:
.....
pawq_param: testvalue
....
```

but it does not work with arrays (default value from parameters.yml.dist is used):

```
$ export PAWQ_PARAM=("testval1", "testval2")
$ export | grep PAWQ
declare -ax PAWQ_PARAM='([0]="testval1," [1]="testval2")'
$ composer install --optimize-autoloader --no-progress --no-interaction;cat app/config/parameters.yml
......
# This file is auto-generated during the composer install
parameters:
.....
    pawq_param:
        - val1
        - val2
```

The output in parameters.yml should be:
```
 pawq_param:
       - testval1
       - testval2
```

**Comment by stof** [comment]
you can put a Yaml array in the env variable, which is the way to pass array values.

I was not even aware that there is a way to export bash arrays as env variables btw (and I don't think it plays well with the PHP logic reading env variables)

**Comment by crashev** [comment]
Ok it looks like mentioned above arrays are not a core/standard but a function of certain sh shell.

@stof: but still can't find a way to use it. If I set env variable like this:

```
$ export PAWQ_PARAM="
> - val1
> - val2
> - val3
> "
```

the result is in generated parameters.yml is:
```
....
pawq_param: "- val1\n- val2\n- val3"
.....
```

**Comment by crashev** [comment]
I think I found fix for this Inline::parse() should be changed to Yaml::parse() and then everything is just fine. I will probably submit PR for this tomorrow

**Comment by OskarStark** [comment]
refs #81

**Comment by stof** [comment]
@crashev use the inline syntax for Yaml arrays, not the mutliline syntax (btw, a JSON string is a valid inline Yaml string)

**Comment by crashev** [comment]
@stof did not know about inline syntax and seems to work just fine, thanks and seems that right now my pull request wont be needed

**Comment by vincentlepot** [comment]
What would be nice is the ability to override only part of a yaml object in a parameter.yml.

Eg:
```
parameters:
  an_object:
    a_first_key: the_value
    a_second_key: the_value
```
Link `an_object` to an environment variable is easy, but how can I use an environment variable to modify only `a_second_key`?

**Comment by samuel4x4** [comment]
Hello, I just noticed this issue in my project, I use there an array parameters and I see the new array elements are not checked from parameters.yml to parameters.yml.dist. Is this issue fixed or is there at least an intention to do it? Thanks

**Comment by stof** [comment]
@samuel4x4 Symfony parameters are not nested. There is a single parameter here, named `an_object`. And if you already have a value for it in the parameters.yml, its value is kept. The value provided in the dist file is only used as a fallback when the value is not provided anywhere (not env variable providing the value, no existing value in the file and no value provided interactively)

**Comment by samuel4x4** [comment]
@stof I have this parameter in my parameters.yml:

```
app:
   key1: value1
   key2: value2
   key3: value3
```
and this one in parameters.yml.dist:

```
app:
   key1: value1
   key2: value2
   key3: value3
   key4: value4
```
I noticed `composer install` doesn't copy `key4`  in parameters.yml and from MHO it should. `key4` is like a parameter but yaml just let you group them in array if you need it.

Isn't a good idea to have `ScriptHandler::buildParameters` doing this also, not just checking the `app` object without checking inside?

Thanks!
