### ISSUE TITLE
Add build times as parameters

### ISSUE THREAD

**Issue by whyte624** [Incenteev/ParameterHandler#92]
Post install time and post update time (UTC) to parameters.
For example,

```
#parameters.yml
post_install_time: 1321313
post_update_time: 1335456
```

Those parameters could be used for javascript

```
script.js?time=2132313
```

Or memcache namespace.

**Comment by TheRatG** [comment]
:+1:

**Comment by OskarStark** [comment]
:+1:

**Comment by aschempp** [comment]
Looks very similar to #88
