### ISSUE TITLE
Compatibility with Symfony 3.0?

### ISSUE THREAD

**Issue by bibeksigdel33** [Incenteev/ParameterHandler#94]
is this library compatible with symfony 3.0?

**Comment by aschempp** [comment]
Did you check the composer dependencies? ;-)

**Comment by bibeksigdel33** [comment]
it requires symfony/filesystem

**Comment by aschempp** [comment]
Only for development. But I assume that dependency is wrong, so :+1: for the issue :-)

**Comment by bibeksigdel33** [comment]
then it is compatible. right ?

**Comment by aschempp** [comment]
I would say so
